zk1:
  image: vpclub/zookeeper 
  container_name: zk1
  net: host 
#  ports:
#    - 2181:2181
  environment:
   - SERVER_ID=1
   - ADDITIONAL_ZOOKEEPER_1=server.1=localhost:2888:3888
   - ADDITIONAL_ZOOKEEPER_2=server.2=localhost:2889:3889
   - ADDITIONAL_ZOOKEEPER_3=server.3=localhost:2890:3890
   - ADDITIONAL_ZOOKEEPER_4=clientPort=2181
zk2:
  image: vpclub/zookeeper
  container_name: zk2
  net: host
#  ports:
#    - 2181:2181
  environment:
   - SERVER_ID=2
   - ADDITIONAL_ZOOKEEPER_1=server.1=localhost:2888:3888
   - ADDITIONAL_ZOOKEEPER_2=server.2=localhost:2889:3889
   - ADDITIONAL_ZOOKEEPER_3=server.3=localhost:2890:3890
   - ADDITIONAL_ZOOKEEPER_4=clientPort=2182
zk3:
  image: vpclub/zookeeper
  container_name: zk3
  net: host
#  ports:
#    - 2181:2181
  environment:
   - SERVER_ID=3
   - ADDITIONAL_ZOOKEEPER_1=server.1=localhost:2888:3888
   - ADDITIONAL_ZOOKEEPER_2=server.2=localhost:2889:3889
   - ADDITIONAL_ZOOKEEPER_3=server.3=localhost:2890:3890
   - ADDITIONAL_ZOOKEEPER_4=clientPort=2183
