vp-search-consumer:
  image: vpclub/java
  working_dir: /app
  net: host
  volumes:
    - ./app:/app

  command: java -Xmx128m -Xss256k -jar /app/vp-search-consumer-1.0.0.jar --spring.profiles.active=test-lnyp

  ports:
    - 9897:9897
    - 23001:23001

#  environment:
#    HOSTNAME: vpclub
#
#  extra_hosts:
#    vpclub:
#  log_driver: syslog
#  log_opt:
#      syslog-address: "tcp://172.16.45.3:5000"

