otter-manager:
  image: plain/otter_manager
  container_name: dev-otter-manager
  privileged: true
  net: host
  environment:
   ManagerAddr: 172.16.5.90
   ManagerPort: 8080
   MysqlAddr: 172.16.5.90:3306
   MysqlUser: root
   MysqlPwd: "@vpclubdev"
  volumes:
    - ./log:/manager/logs
