kafka:
  image: wurstmeister/kafka
  container_name: kafka
  net: host
  ports:
    - "9092:9092"
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_PORT: 9092
    KAFKA_ADVERTISED_HOST_NAME: 172.16.7.237
    KAFKA_ADVERTISED_PORT: "9092"
    KAFKA_ZOOKEEPER_CONNECT: 172.16.7.236:2181,172.16.7.237:2181
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
    KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    KAFKA_MESSAGE_MAX_BYTES: 5242880
    KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
