kafka-9092:
  image: wurstmeister/kafka
  net: host
  ports:
    - "9092:9092"
  environment:
    KAFKA_BROKER_ID: 0
    KAFKA_PORT: 9092
    KAFKA_ADVERTISED_HOST_NAME: 172.16.7.13
    KAFKA_ADVERTISED_PORT: "9092"
    KAFKA_ZOOKEEPER_CONNECT: 172.16.7.13:2181,172.16.7.13:2182,172.16.7.13:2183
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
    KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    KAFKA_MESSAGE_MAX_BYTES: 5242880
    KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
    KAFKA_LOG_DIR: /tmp/kafka-log-0
    KAFKA_LOG_DIRS: /tmp/kafka-logs-0
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

kafka-9093:
  image: wurstmeister/kafka
  net: host
  ports:
    - "9093:9093"
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_PORT: 9093
    KAFKA_ADVERTISED_HOST_NAME: 172.16.7.13
    KAFKA_ADVERTISED_PORT: "9093"
    KAFKA_ZOOKEEPER_CONNECT: 172.16.7.13:2181,172.16.7.13:2182,172.16.7.13:2183
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
    KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    KAFKA_MESSAGE_MAX_BYTES: 5242880
    KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
    KAFKA_LOG_DIR: /tmp/kafka-log-1
    KAFKA_LOG_DIRS: /tmp/kafka-logs-1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
